// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwF-9fSTV_MXRijzsfh4-VotFjrhoP5p8',
    appId: '1:394681633495:android:9e051a6d87191b09e7fe92',
    messagingSenderId: '394681633495',
    projectId: 'public-health-info-d30ee',
    storageBucket: 'public-health-info-d30ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfWHWjNlcMFX3GqMYA49mCNRfeHJddfs',
    appId: '1:394681633495:ios:aec577b9bab26528e7fe92',
    messagingSenderId: '394681633495',
    projectId: 'public-health-info-d30ee',
    storageBucket: 'public-health-info-d30ee.appspot.com',
    iosClientId: '394681633495-41bo377ic4r261947gj58abfb416g3im.apps.googleusercontent.com',
    iosBundleId: 'com.hemcapstone.phi',
  );
}
